"""
pyPetrograph: RGB pixel labeling plus a multimodal object pipeline.

RGB notebook: wand/polygon labels → LightGBM class maps → area %.
Multimodal notebook: align layers → physics channels → grain/pore outlines →
object table → group/name → LightGBM names the rest → QFL / IGV / Folk & Ward.
Mineral-map notebook: flat-color mineral maps → legend snap → grains → per-class counts with uncertainty.
"""

from __future__ import annotations

__version__ = "0.0.5"

from pyPetrograph.common.constants import (
    CACHE_SUBDIR,
    DEFAULT_CLASSES,
    DEFAULT_EMBED_FEATURE_TOGGLES,
    DEFAULT_FEATURE_TOGGLES,
    DEFAULT_FIGURE_DPI,
    DEFAULT_METHOD,
    DEFAULT_N_JOBS,
    DEFAULT_PREVIEW_DPI,
    DEFAULT_PREVIEW_TARGET_MP,
    DEFAULT_SURE_PROBA,
    DEFAULT_Y_TARGET,
    LABELS_SUBDIR,
    METHODS,
    MODELS_SUBDIR,
    PREDICTIONS_SUBDIR,
    REQUIRED_PACKAGES,
    SAM2_PACKAGES,
    SEG_PACKAGES,
    SUPPORTED_EXTENSIONS,
    UNIVERSAL_MODEL_NAME,
)
from pyPetrograph.common.image_io import load_image
from pyPetrograph.common.notebook_runners import (
    print_label_summary,
    print_train_metrics,
    run_feature_preview,
    run_predict_cell,
    run_scene_feature_preview,
    run_train_cell,
)
from pyPetrograph.common.paths import (
    check_and_install_packages,
    cleanup_legacy_outputs,
    get_output_dir,
    relpath_display,
    set_output_dir,
    stem_paths,
)
from pyPetrograph.common.session import Session
from pyPetrograph.common.ui import (
    build_ui,
    launch_app,
    select_images,
    # private subprocess entrypoints re-exported for child processes
    _run_label_gui_from_config,
    _run_qt_picker_from_config,
    launch_app_inplace,
)
from pyPetrograph.image_processing.brightness import normalize_brightness, relative_luminance
from pyPetrograph.image_processing.features import (
    build_feature_stack,
    downsample_to_approx_mp,
    resolve_view_target_mp,
    screen_view_target_mp,
)
from pyPetrograph.image_processing.fractions import compute_fractions, compute_fractions_uncertain
from pyPetrograph.labeling_ml.polygons import magic_wand_to_polygon
from pyPetrograph.labeling_ml.predict import predict_image, predict_image_proba
from pyPetrograph.align import (
    Scene,
    launch_align,
    load_scene,
    save_scene,
    embed_scene,
    stack_feature_slots,
    slot_kind,
    xpl_slot,
)
from pyPetrograph.fuse import (
    fit_extinction,
    phi_deg_from_cos_sin,
    MIN_ANGLES,
    ChannelStack,
    DEFAULT_CHANNEL_TOGGLES,
    build_channel_stack,
    channel_set_id,
    channels_paths,
    save_channel_stack,
    load_channel_stack,
    iter_tiles,
    apply_tiled,
    axioscan_layers,
    axioscan_scale_folder,
    add_axioscan_layers,
    run_channel_preview,
)
from pyPetrograph.objects import (
    run_watershed,
    watershed_labels,
    init_grain_unet,
    train_grain_unet,
    predict_grain_unet,
    grain_unet_path,
    run_outlines,
    compare_outlines,
    launch_grain_qc,
    launch_ppl_grain_qc,
    load_grain_qc,
    load_ppl_grain_qc,
    grain_qc_paths,
    load_grain_mask,
    overlay_labels,
    ensure_seg_weights,
    seg_setup_hint,
    build_object_table,
    build_object_table_from_stack,
    save_object_table,
    load_object_table,
    cluster_objects,
    launch_montage_labeler,
    load_object_labels,
    apply_object_labels,
    object_model_path,
    train_object_classifier,
    predict_object_classes,
    save_classes,
    load_classes,
    compute_object_stats,
    save_object_stats,
    load_object_stats,
)
from pyPetrograph.mineral_map import (
    read_legend_swatches,
    legend_from_image,
    check_legend,
    snap_to_legend,
    read_rgba,
    absorb_specks,
    label_grains,
    grain_table,
    grains_to_geojson,
    class_rgb,
    count_grains,
    pivot_counts,
    format_counts,
    mineralmap_paths,
    process_image,
    process_folder,
)

__all__ = [
    "SUPPORTED_EXTENSIONS",
    "DEFAULT_Y_TARGET",
    "DEFAULT_N_JOBS",
    "DEFAULT_METHOD",
    "METHODS",
    "DEFAULT_CLASSES",
    "REQUIRED_PACKAGES",
    "SEG_PACKAGES",
    "SAM2_PACKAGES",
    "MODELS_SUBDIR",
    "PREDICTIONS_SUBDIR",
    "LABELS_SUBDIR",
    "CACHE_SUBDIR",
    "UNIVERSAL_MODEL_NAME",
    "stem_paths",
    "set_output_dir",
    "get_output_dir",
    "relpath_display",
    "cleanup_legacy_outputs",
    "load_image",
    "normalize_brightness",
    "relative_luminance",
    "DEFAULT_FEATURE_TOGGLES",
    "DEFAULT_EMBED_FEATURE_TOGGLES",
    "DEFAULT_PREVIEW_TARGET_MP",
    "DEFAULT_PREVIEW_DPI",
    "DEFAULT_FIGURE_DPI",
    "check_and_install_packages",
    "magic_wand_to_polygon",
    "build_feature_stack",
    "downsample_to_approx_mp",
    "screen_view_target_mp",
    "resolve_view_target_mp",
    "Session",
    "select_images",
    "build_ui",
    "launch_app",
    "print_label_summary",
    "run_feature_preview",
    "run_scene_feature_preview",
    "run_train_cell",
    "print_train_metrics",
    "run_predict_cell",
    "predict_image",
    "predict_image_proba",
    "compute_fractions",
    "compute_fractions_uncertain",
    "__version__",
    "DEFAULT_SURE_PROBA",
    "Scene",
    "launch_align",
    "save_scene",
    "load_scene",
    "embed_scene",
    "stack_feature_slots",
    "launch_ppl_grain_qc",
    "load_ppl_grain_qc",
    "grain_qc_paths",
    "load_grain_mask",
    "seg_setup_hint",
    "slot_kind",
    "xpl_slot",
    "fit_extinction",
    "phi_deg_from_cos_sin",
    "MIN_ANGLES",
    "ChannelStack",
    "DEFAULT_CHANNEL_TOGGLES",
    "build_channel_stack",
    "channel_set_id",
    "channels_paths",
    "save_channel_stack",
    "load_channel_stack",
    "iter_tiles",
    "apply_tiled",
    "axioscan_layers",
    "axioscan_scale_folder",
    "add_axioscan_layers",
    "run_channel_preview",
    "run_watershed",
    "watershed_labels",
    "init_grain_unet",
    "train_grain_unet",
    "predict_grain_unet",
    "grain_unet_path",
    "run_outlines",
    "compare_outlines",
    "launch_grain_qc",
    "load_grain_qc",
    "overlay_labels",
    "ensure_seg_weights",
    "build_object_table",
    "build_object_table_from_stack",
    "save_object_table",
    "load_object_table",
    "cluster_objects",
    "launch_montage_labeler",
    "load_object_labels",
    "apply_object_labels",
    "object_model_path",
    "train_object_classifier",
    "predict_object_classes",
    "save_classes",
    "load_classes",
    "compute_object_stats",
    "save_object_stats",
    "load_object_stats",
    "read_legend_swatches",
    "legend_from_image",
    "check_legend",
    "snap_to_legend",
    "read_rgba",
    "absorb_specks",
    "label_grains",
    "grain_table",
    "grains_to_geojson",
    "class_rgb",
    "count_grains",
    "pivot_counts",
    "format_counts",
    "mineralmap_paths",
    "process_image",
    "process_folder",
]
